### ISSUE TITLE
bash or zsh

### ISSUE THREAD

**Issue by vembalarashid** [demhademha/tweak-development-guide#8]
typing echo $SHELL. This will return either /usr/bin/bash or /usr/bin/zsh

But mine shows /bin/ash

Why ?

**Comment by Silverethical** [comment]
[The following answer was originally posted [here](https://apple.stackexchange.com/a/159702)]

That is because you are using the ash shell. Normally you can change this via the chsh command, but from what I gathered iOS doesn't have this command. So you need to edit /etc/passwd and /etc/master.passwd (as root) and change the shell to /bin/bash.
So it should look something like this:
```
root:*:0:0:System Administrator:rootUser:/var/root:/bin/bash
mobile:*:501:501:Mobile User:/var/mobile:/bin/bash
```

**Comment by Silverethical** [comment]
> typing echo $SHELL. This will return either /usr/bin/bash or /usr/bin/zsh
> 
> But mine shows /bin/ash
> 
> Why ?

That is because you are using the Almquist shell (AKA ash). 


The following solution has been originally posted [here](https://apple.stackexchange.com/a/159702)

Normally you can change this via the chsh command, but from what I gathered iOS doesn't have this command. So you need to edit /etc/passwd and /etc/master.passwd (as root) and change the shell to /bin/bash.
So it should look something like this:
```
root:*:0:0:System Administrator:root:/var/root:/bin/bash
mobile:*:501:501:Mobile User:/var/mobile:/bin/bash
```

**Comment by demhademha** [comment]
Ash is alpine's shell, make sure that you  are sshed into your device. 
You can refer to chapter 1 if you've forgotten how to do that.

**Comment by demhademha** [comment]
Closed due to a lack of response. 
You can reopen this issue
